In [2]:
import warnings
warnings.filterwarnings('ignore')

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
test_df=pd.read_csv('Data/test.csv')
test_df.head()

,Unnamed: 0,Negara/Tahun,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,...,Emisi Pupuk Kandang Di Padang Rumput,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total
0,0,Afghanistan/2015,0.8454,0.0,403.3181,642.8800,0.0,81.852555,440.0315,-246.2191,...,2719.1528,797.9007,0.0,0.0,NaN,25368923.0,8367571.0,17071446.0,16682054.0,12652.876111
1,1,Afghanistan/2016,1.6558,0.0,387.6130,466.4800,0.0,54.909681,340.8931,154.6574,...,2692.9570,793.9377,0.0,0.0,NaN,25985093.0,8670939.0,17520861.0,17115346.0,12988.384380
2,2,Afghanistan/2017,0.4015,0.0,344.6447,429.0518,0.0,55.148427,345.7609,154.6574,...,2680.8381,768.6802,0.0,0.0,NaN,26558609.0,8971472.0,18028696.0,17614722.0,12786.218762
3,3,Afghanistan/2018,0.2008,0.0,291.7838,460.7529,0.0,72.743150,407.6310,154.6574,...,2716.9079,789.3364,0.0,0.0,NaN,27099874.0,9273302.0,18549862.0,18136922.0,13054.982649
4,4,Afghanistan/2019,7.1050,0.0,395.2689,499.9176,0.0,80.806938,489.7252,154.6574,...,2557.4329,766.5012,0.0,0.0,NaN,27626382.0,9582625.0,19090409.0,18679089.0,13354.360473

In [6]:
train_df=pd.read_csv('Data/train.csv')
train_df

,Unnamed: 0,Negara/Tahun,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,...,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total,Peningkatan Suhu Rata - Rata Â° C
0,0,Afghanistan/1990,14.7237,0.0557,205.6077,686.0000,0.0,11.807483,63.1152,-2388.8030,...,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,1,Afghanistan/1991,14.7237,0.0557,209.4971,678.1600,0.0,11.712073,61.2125,-2388.8030,...,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,2,Afghanistan/1992,14.7237,0.0557,196.5341,686.0000,0.0,11.712073,53.3170,-2388.8030,...,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,3,Afghanistan/1993,14.7237,0.0557,230.8175,686.0000,0.0,11.712073,54.3617,-2388.8030,...,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,4,Afghanistan/1994,14.7237,0.0557,242.0494,705.6000,0.0,11.712073,53.9874,-2388.8030,...,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5598,5598,Zimbabwe/2010,2795.6192,283.6316,109.3055,3.0243,0.0,87.000000,157.6366,262.6108,...,302.3508,0.0,0.0,2074.1869,9410211.0,4676106.0,6034165.0,6805605.0,23601.395453,0.911917
5599,5599,Zimbabwe/2011,2918.2098,168.1659,100.7798,3.7456,0.0,94.000000,268.6740,648.0808,...,312.2478,0.0,0.0,966.3719,9636932.0,4749717.0,6114111.0,6911674.0,23470.631605,0.191167
5600,5600,Zimbabwe/2012,2164.8953,259.4249,103.8422,5.5527,0.0,91.000000,304.6578,648.0808,...,314.3433,0.0,0.0,908.2629,9880721.0,4830105.0,6223803.0,7041528.0,22903.232305,0.337000
5601,5601,Zimbabwe/2013,1544.9329,238.1898,96.8978,5.8016,0.0,73.000000,338.5506,648.0808,...,317.9359,0.0,0.0,546.0138,10138667.0,4915839.0,6363142.0,7192279.0,22245.497305,0.089667
5602,5602,Zimbabwe/2014,1706.5216,166.6056,94.2907,7.3598,0.0,65.000000,306.0107,648.0808,...,240.2096,0.0,0.0,520.7873,10402274.0,5009401.0,6508226.0,7347527.0,21653.810678,0.096333

In [12]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1362 entries, 0 to 1361
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Negara/Tahun                                 1362 non-null   object
 1   Emisi Savanna Api                            1356 non-null   float64
 2   Emisi Kebakaran Hutan                        1344 non-null   float64
 3   Emisi Residu Tanaman                         1091 non-null   float64
 4   Emisi Budidaya Padi                          1362 non-null   float64
 5   Emisi Tanah Organik Yang Dikeringkan (Co2)   1362 non-null   float64
 6   Emisi Pembuatan Pestisida                    1362 non-null   float64
 7   Emisi Transportasi Makanan                   1362 non-null   float64
 8   Lahan Hutan                                  1266 non-null   float64
 9   Konversi Hutan Bersih                        1266 non-null   float64
 10  Emisi Konsumsi Rumah Tangga Makanan          1278 non-null   float64
 11  Emisi Ritel Makanan                          1362 non-null   float64
 12  Emisi Penggunaan Listrik Di Pertanian        1362 non-null   float64
 13  Emisi Kemasan Makanan                        1362 non-null   float64
 14  Emisi Sistem Agrifood Pembuangan Limbah      1362 non-null   float64
 15  Emisi Pengolahan Makanan                     1362 non-null   float64
 16  Emisi Manufaktur Pupuk                       1362 non-null   float64
 17  Emisi IPPU                                   1218 non-null   float64
 18  Emisi Kotoran Diterapkan Pada Tanah          1186 non-null   float64
 19  Emisi Pupuk Kandang Di Padang Rumput         1362 non-null   float64
 20  Emisi Manajemen Pupuk                        1186 non-null   float64
 21  Emisi Kebakaran Di Tanah Organik             1362 non-null   float64
 22  Emisi Kebakaran Di Hutan Tropis Yang Lembab  1332 non-null   float64
 23  Penggunaan Energi Di Pertanian               1188 non-null   float64
 24  Populasi Pedesaan                            1362 non-null   float64
 25  Populasi Perkotaan                           1362 non-null   float64
 26  Total Populasi - Pria                        1362 non-null   float64
 27  Total Populasi - Wanita                      1362 non-null   float64
 28  Emisi Total                                  1362 non-null   float64
dtypes: float64(28), object(1)
memory usage: 308.7+ KB

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5603 entries, 0 to 5602
Data columns (total 30 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Negara/Tahun                                 5603 non-null   object
 1   Emisi Savanna Api                            5578 non-null   float64
 2   Emisi Kebakaran Hutan                        5528 non-null   float64
 3   Emisi Residu Tanaman                         4485 non-null   float64
 4   Emisi Budidaya Padi                          5603 non-null   float64
 5   Emisi Tanah Organik Yang Dikeringkan (Co2)   5603 non-null   float64
 6   Emisi Pembuatan Pestisida                    5603 non-null   float64
 7   Emisi Transportasi Makanan                   5603 non-null   float64
 8   Lahan Hutan                                  5206 non-null   float64
 9   Konversi Hutan Bersih                        5206 non-null   float64
 10  Emisi Konsumsi Rumah Tangga Makanan          5214 non-null   float64
 11  Emisi Ritel Makanan                          5603 non-null   float64
 12  Emisi Penggunaan Listrik Di Pertanian        5603 non-null   float64
 13  Emisi Kemasan Makanan                        5603 non-null   float64
 14  Emisi Sistem Agrifood Pembuangan Limbah      5603 non-null   float64
 15  Emisi Pengolahan Makanan                     5603 non-null   float64
 16  Emisi Manufaktur Pupuk                       5603 non-null   float64
 17  Emisi IPPU                                   5004 non-null   float64
 18  Emisi Kotoran Diterapkan Pada Tanah          4851 non-null   float64
 19  Emisi Pupuk Kandang Di Padang Rumput         5603 non-null   float64
 20  Emisi Manajemen Pupuk                        4851 non-null   float64
 21  Emisi Kebakaran Di Tanah Organik             5603 non-null   float64
 22  Emisi Kebakaran Di Hutan Tropis Yang Lembab  5478 non-null   float64
 23  Penggunaan Energi Di Pertanian               4821 non-null   float64
 24  Populasi Pedesaan                            5603 non-null   float64
 25  Populasi Perkotaan                           5603 non-null   float64
 26  Total Populasi - Pria                        5603 non-null   float64
 27  Total Populasi - Wanita                      5603 non-null   float64
 28  Emisi Total                                  5603 non-null   float64
 29  Peningkatan Suhu Rata - Rata Â° C             5603 non-null   float64
dtypes: float64(29), object(1)
memory usage: 1.3+ MB

# Preprocessing

In [7]:
test_df.drop(columns=test_df.columns[0], inplace=True)

In [8]:
train_df.drop(columns=train_df.columns[0], inplace=True)

In [10]:
test_df.isnull().sum()

Negara/Tahun                                     0
Emisi Savanna Api                                6
Emisi Kebakaran Hutan                           18
Emisi Residu Tanaman                           271
Emisi Budidaya Padi                              0
Emisi Tanah Organik Yang Dikeringkan (Co2)       0
Emisi Pembuatan Pestisida                        0
Emisi Transportasi Makanan                       0
Lahan Hutan                                     96
Konversi Hutan Bersih                           96
Emisi Konsumsi Rumah Tangga Makanan             84
Emisi Ritel Makanan                              0
Emisi Penggunaan Listrik Di Pertanian            0
Emisi Kemasan Makanan                            0
Emisi Sistem Agrifood Pembuangan Limbah          0
Emisi Pengolahan Makanan                         0
Emisi Manufaktur Pupuk                           0
Emisi IPPU                                     144
Emisi Kotoran Diterapkan Pada Tanah            176
Emisi Pupuk Kandang Di Padang Rumput             0
Emisi Manajemen Pupuk                          176
Emisi Kebakaran Di Tanah Organik                 0
Emisi Kebakaran Di Hutan Tropis Yang Lembab     30
Penggunaan Energi Di Pertanian                 174
Populasi Pedesaan                                0
Populasi Perkotaan                               0
Total Populasi - Pria                            0
Total Populasi - Wanita                          0
Emisi Total                                      0
dtype: int64

In [11]:
train_df.isnull().sum()

Negara/Tahun                                      0
Emisi Savanna Api                                25
Emisi Kebakaran Hutan                            75
Emisi Residu Tanaman                           1118
Emisi Budidaya Padi                               0
Emisi Tanah Organik Yang Dikeringkan (Co2)        0
Emisi Pembuatan Pestisida                         0
Emisi Transportasi Makanan                        0
Lahan Hutan                                     397
Konversi Hutan Bersih                           397
Emisi Konsumsi Rumah Tangga Makanan             389
Emisi Ritel Makanan                               0
Emisi Penggunaan Listrik Di Pertanian             0
Emisi Kemasan Makanan                             0
Emisi Sistem Agrifood Pembuangan Limbah           0
Emisi Pengolahan Makanan                          0
Emisi Manufaktur Pupuk                            0
Emisi IPPU                                      599
Emisi Kotoran Diterapkan Pada Tanah             752
Emisi Pupuk Kandang Di Padang Rumput              0
Emisi Manajemen Pupuk                           752
Emisi Kebakaran Di Tanah Organik                  0
Emisi Kebakaran Di Hutan Tropis Yang Lembab     125
Penggunaan Energi Di Pertanian                  782
Populasi Pedesaan                                 0
Populasi Perkotaan                                0
Total Populasi - Pria                             0
Total Populasi - Wanita                           0
Emisi Total                                       0
Peningkatan Suhu Rata - Rata Â° C                  0
dtype: int64